// <auto-generated />
using AgenciaDeViagem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AgenciaDeViagem.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AgenciaDeViagem.Model.Destino", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DestinoGenre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("destino_genre");

                    b.Property<string>("DestinoName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("destino_name");

                    b.Property<decimal>("DestinoPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("destino_price");

                    b.Property<string>("DestinoURL")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("destino_url");

                    b.HasKey("Id");

                    b.ToTable("destinos");
                });
#pragma warning restore 612, 618
        }
    }
}
